// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GroupDeleteTest {
    private WebDriver driver;


    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        driver.get("http://localhost/addressbook/index.php");
        driver.manage().window().setSize(new Dimension(1217, 743));
        driver.findElement(By.name("user")).sendKeys("admin");
        driver.findElement(By.name("pass")).click();
        driver.findElement(By.name("pass")).sendKeys("secret");
        driver.findElement(By.xpath("//input[@value=\'Login\']")).click();
    }

    @AfterEach
    public void tearDown() {
        //driver.findElement(By.linkText("Logout")).click();
        driver.quit();

    }

    @Test
    public void canDeleteGroup() {
        driver.findElement(By.linkText("groups")).click();
        List<WebElement> checkboxesBefore = driver.findElements(By.name("selected[]"));
        int before = checkboxesBefore.size();
        if (before > 0) {
            checkboxesBefore.get(0).click();
        } else {
            throw new AssertionError("Группы отсутсвуют");
        }
        driver.findElement(By.name("delete")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("group page"))).click();
        List<WebElement> checkboxesAfter = driver.findElements(By.name("selected[]"));
        int after = checkboxesAfter.size();
        assertEquals(before - 1, after);
    }

    @Test
    public void canDeleteGroupWithCreation() {
        if (!isElementPresent(By.name("new"))) {
            driver.findElement(By.linkText("groups")).click();
        }
        List<WebElement> checkboxesBefore = driver.findElements(By.name("selected[]"));
        if (!isElementPresent(By.name("selected[]"))) {
            driver.findElement(By.name("new")).click();
            driver.findElement(By.id("content")).click();
            driver.findElement(By.name("group_name")).click();
            driver.findElement(By.name("group_name")).sendKeys("New group 1");
            driver.findElement(By.name("group_header")).click();
            driver.findElement(By.name("group_header")).sendKeys("Header1");
            driver.findElement(By.name("group_footer")).click();
            driver.findElement(By.name("group_footer")).sendKeys("Footer1");
            driver.findElement(By.name("submit")).click();
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.elementToBeClickable(By.linkText("group page"))).click();
        }
        driver.findElement(By.name("delete")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("group page"))).click();
    }

    private boolean isElementPresent(By locator) {
        try {
            driver.findElement(locator);
            return true;
        } catch (NoSuchElementException exception) {
            return false;
        }
    }

}
